/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aptech.project2.GUI;

import aptech.project2.common.DateCommon;
import aptech.project2.common.ValidateCommon;
import aptech.project2.constant.Constant;
import aptech.project2.model.Catalog;
import aptech.project2.model.Orders;
import aptech.project2.model.Transaction;
import aptech.project2.model.User;
import aptech.project2.service.CatalogJpaController;
import aptech.project2.service.OrderServices;
import aptech.project2.service.OrdersJpaController;
import aptech.project2.service.TransactionJpaController;
import aptech.project2.service.TransactionService;
import aptech.project2.service.UserJpaController;
import aptech.project2.service.UserService;
import aptech.project2.service.exceptions.NonexistentEntityException;
import aptech.project2.utilities.JPAUtil;
import com.mysql.jdbc.RowData;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TransactionMangerment extends javax.swing.JFrame {

    private Long transactionId = null;
    private Date currentDate;
    private Transaction transaction = null;
    private final String DELETE_SUCCESS = "Xoá Thành Công";
    public final static String DA_HOAN_THANH = "Đã Hoàn Thành";
    public final static String CHUA_HOAN_THANH = "Chưa Hoàn Thành ";
    public final static String DANG_HOAN_THANH = "Đang Hoàn Thành";

    /**
     * Creates new form UserManager
     */
    public TransactionMangerment() {
        initComponents();
        this.loadData();
        renderComboOrder();
        renderComboUser();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        it_product = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        it_orders = new javax.swing.JLabel();
        it_profile = new javax.swing.JLabel();
        it_catalog = new javax.swing.JLabel();
        lbTransaction = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboAction = new javax.swing.JComboBox<>();
        lbAction = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbAction1 = new javax.swing.JLabel();
        lbOrder = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        jComboBoxUser = new javax.swing.JComboBox<>();
        jComboBoxOrder = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtmessage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(35, 46, 66));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.lightGray);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/ic_settings.png"))); // NOI18N
        jLabel9.setText("Setting");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.lightGray);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/ic_home.png"))); // NOI18N
        jLabel10.setText("DashBoard");

        it_product.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        it_product.setForeground(java.awt.Color.lightGray);
        it_product.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        it_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/ic_product.png"))); // NOI18N
        it_product.setText("Product ");
        it_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                it_productMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/logout.png"))); // NOI18N
        jLabel17.setText("Log Out");

        it_orders.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        it_orders.setForeground(java.awt.Color.lightGray);
        it_orders.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        it_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/ic_orders.png"))); // NOI18N
        it_orders.setText("Orders");
        it_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                it_ordersMouseClicked(evt);
            }
        });

        it_profile.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        it_profile.setForeground(java.awt.Color.lightGray);
        it_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/ic_user.png"))); // NOI18N
        it_profile.setText("Profile");
        it_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                it_profileMouseClicked(evt);
            }
        });

        it_catalog.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        it_catalog.setForeground(java.awt.Color.lightGray);
        it_catalog.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        it_catalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/ic_catalog.png"))); // NOI18N
        it_catalog.setText("Provider");
        it_catalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                it_catalogMouseClicked(evt);
            }
        });

        lbTransaction.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbTransaction.setForeground(java.awt.Color.lightGray);
        lbTransaction.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aptech/project2/image/ic_transaction.png"))); // NOI18N
        lbTransaction.setText("Transaction");
        lbTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTransactionMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SHOWROOM CAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(it_product, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(it_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(it_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(it_catalog, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(it_product, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(it_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(it_catalog, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(it_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaction Managerment\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jComboAction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionActionPerformed(evt);
            }
        });

        lbAction.setText("Lời Nhắn");

        jLabel4.setText("Mã Người Dùng");

        lbAction1.setText("Tình Trạng");

        lbOrder.setText("Mã Hoá Đơn");

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane2.setViewportView(txtMessage);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOrder, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboAction, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addGap(84, 84, 84)
                .addComponent(lbAction, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAction, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        btnadd.setText("THÊM");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("CẬP NHẬT");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("XOÁ");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        txtmessage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtmessage.setText("Giao Dịch");

        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Người Dùng", "Mã Hoá Đơn", "Tình Trạng", "Lời Nhắn"
            }
        ));
        tblTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransactionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTransaction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void renderComboOrder() {
        List<Orders> orders = OrdersJpaController.getInstance().findOrdersEntities();
        orders.forEach(a -> {
            if (!a.getOrderNo().isEmpty()) {
                jComboBoxOrder.addItem(a.getOrderNo());
            }
        });
    }

    private void renderComboUser() {
        List<User> users = UserService.getInstace().findAll();
        users.forEach(a -> {
            if (!a.getName().isEmpty()) {
                jComboBoxUser.addItem(a.getId().toString());
            }
        });
    }

    private void loadData() {
        List<Transaction> transactions = TransactionService.getInstance().findAll();
        DefaultTableModel tableModel = (DefaultTableModel) tblTransaction.getModel();
        tableModel.setRowCount(0);
        jComboAction.removeAllItems();
        jComboAction.addItem(DA_HOAN_THANH);
        jComboAction.addItem(CHUA_HOAN_THANH);
        jComboAction.addItem(DANG_HOAN_THANH);
        transactions.stream().forEach(t -> {
            String action = selectAction(t.getAction());
            Object[] rowData = new Object[]{
                t.getId(), t.getUserId().getId(), t.getOrderId().getOrderNo(), action, t.getMessage()};
            tableModel.addRow(rowData);

        });
    }
    private void lbTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTransactionMouseClicked
        // TODO add your handling code here:
        TransactionMangerment mf = new TransactionMangerment();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbTransactionMouseClicked

    private void it_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_it_productMouseClicked
        // TODO add your handling code here:
        ProductManagement pm = new ProductManagement();
        pm.setVisible(true);
        dispose();
    }//GEN-LAST:event_it_productMouseClicked

    private void it_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_it_ordersMouseClicked
        // TODO add your handling code here:
        OrderMangerment om = new OrderMangerment();
        om.setVisible(true);
        dispose();
    }//GEN-LAST:event_it_ordersMouseClicked

    private void it_catalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_it_catalogMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_it_catalogMouseClicked

    private void it_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_it_profileMouseClicked
        // TODO add your handling code here:
        UserManager um = new UserManager();
        um.setVisible(true);
        dispose();
    }//GEN-LAST:event_it_profileMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        Transaction transaction = new Transaction();

        String userID = (String) jComboBoxUser.getSelectedItem();
        System.out.println("userId" + Integer.parseInt(userID));
        User user = UserService.getInstace().find(Integer.parseInt(userID));
        String message = txtMessage.getText();
        System.out.println("message " + message);
        int action = (int) jComboAction.getSelectedItem();
        System.out.println("action" + action);
        String order = (String) jComboBoxOrder.getSelectedItem();
        System.out.println("orderNo" + order);
        Orders o = OrderServices.getInstance().findOrderByOrderNo(order);
        System.out.println("orderId " + o);

        if (message == "" || message.trim().equals("")) {
            txtmessage.setText("Lời Nhắn không được để trống!");
            txtmessage.setForeground(Color.red);
        } else {

            transaction.setUserId(user);
            transaction.setAction((short) action);
            transaction.setMessage(message);
            transaction.setOrderId(o);
            TransactionService.getInstance().create(transaction);

            loadData();
            txtmessage.setText("Thêm thành công giao dịch  mã " + transaction.getId());
            System.out.println("create-------------------------------------\n");
            txtmessage.setForeground(Color.GREEN);

        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String userID = (String) jComboBoxUser.getSelectedItem();
        System.out.println("userId" + Integer.parseInt(userID));
        User user = UserService.getInstace().find(Integer.parseInt(userID));
        String message = txtMessage.getText();
        System.out.println("message " + message);
        String action = (String) jComboAction.getSelectedItem();
        System.out.println("action----"+ action);
        int newAction = convertActionToInt(action);
        String order = (String) jComboBoxOrder.getSelectedItem();
        Orders o = OrderServices.getInstance().findOrderByOrderNo(order);

        if (message == "" || message.trim().equals("")) {
            txtmessage.setText("Lời Nhắn không được để trống!");
            txtmessage.setForeground(Color.red);
        } else {

            transaction.setUserId(user);
            transaction.setAction((short) newAction);
            transaction.setMessage(message);
            transaction.setOrderId(o);
            
            TransactionService.getInstance().edit(transaction);
            loadData();
            txtmessage.setText("Cập nhật thành công giao dịch: " + transaction.getId());
            txtmessage.setForeground(Color.GREEN);

        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        if (transactionId == null) {
            txtmessage.setText("Bạn chưa chọn giao dịch!");
            txtmessage.setForeground(Color.red);
            return;
        } else {
            String check = "Bạn có chắc chắn muốn xóa giao dịch:" + transactionId + " không ?";
            int choose = JOptionPane.showConfirmDialog(null, check,
                    "Xác Nhận Xoá", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
            if (choose == 0) {
                try {
                    TransactionService.getInstance().delteById(transactionId);
                    txtmessage.setText("Xóa thành công giao dịch   " + transactionId + " !");
                    txtmessage.setForeground(Color.GREEN);
                    transactionId = null;
                    this.loadData();
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(UserManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jComboActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboActionActionPerformed

    private void tblTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransactionMouseClicked

        transactionId = Long.parseLong(tblTransaction.getModel().getValueAt(tblTransaction.getSelectedRow(), 0).toString());

        System.out.println("-----------------------transacionID: " + transactionId);

        this.displayDetail(transactionId);
    }//GEN-LAST:event_tblTransactionMouseClicked

    private String selectAction(int actionId) {
        String action = "";
        if (actionId == 0) {
            action = CHUA_HOAN_THANH;
        } else if (actionId == 1) {
            action = DA_HOAN_THANH;
        } else {
            action = DANG_HOAN_THANH;
        }
        return action;
    }

    private Short convertActionToInt(String action) {
        Short actionId = null;
        if (action == CHUA_HOAN_THANH) {
            actionId = 0;
        } else if (action == DA_HOAN_THANH) {
            actionId = 1;
        } else {
            actionId = 2;
        }
        return actionId;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionMangerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionMangerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionMangerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionMangerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionMangerment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel it_catalog;
    private javax.swing.JLabel it_orders;
    private javax.swing.JLabel it_product;
    private javax.swing.JLabel it_profile;
    private javax.swing.JComboBox<String> jComboAction;
    private javax.swing.JComboBox<String> jComboBoxOrder;
    private javax.swing.JComboBox<String> jComboBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAction;
    private javax.swing.JLabel lbAction1;
    private javax.swing.JLabel lbOrder;
    private javax.swing.JLabel lbTransaction;
    private javax.swing.JTable tblTransaction;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JLabel txtmessage;
    // End of variables declaration//GEN-END:variables

    private void displayDetail(Long transactionId) {
        this.transaction = TransactionService.getInstance().find(transactionId);

        jComboBoxUser.setSelectedItem(transaction.getUserId().getId().toString());
        jComboBoxOrder.setSelectedItem(transaction.getOrderId().getOrderNo());
        System.out.println("getAction" + transaction.getAction());
        int action = transaction.getAction();
        String newAction = selectAction(action);
        jComboAction.setSelectedItem(newAction);
        txtMessage.setText(transaction.getMessage());
    }

}
